spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  jmx:
    enabled: true
  data:
    rest:
      base-path: /datarest
management:
  endpoints:
    web:
      exposure:
        include: metrics, health, library, loggers, logfile # prometheus, explorer - доступ к конкретным конечным точкам
  endpoint:
    health:
      show-details: always # дополнительная информация показывается всем пользователям
logging:
  file:
    name: spring-18-book.log
  level:
    root: info # Logging Level